---
# security
- ansible.builtin.import_tasks: tasks/password-manager/git-credential-helper.yml
  tags: git-helper

# runtime manager
- name: Install mise
  ansible.builtin.import_tasks: tasks/runtime-manager/mise.yml
  tags: mise

# docker
- name: Install docker
  ansible.builtin.import_tasks: tasks/virtualization/docker.yml
  tags: docker

# aws ssm
- name: Install ssm
  ansible.builtin.import_tasks: tasks/aws/ssm.yml
  tags: ssm
