---
# security
- ansible.builtin.import_tasks: tasks/password-manager/git-credential-helper.yml
  tags: git-helper

# runtime manager
- name: Install mise
  ansible.builtin.import_tasks: tasks/runtime-manager/mise.yml
  tags: mise
