---
- name: 関連ライブラリのインストール
  ansible.builtin.set_fact:
    packages:
      - build-essential
      - libglib2.0-dev
      - libsecret-1-dev

- name: Import installer
  ansible.builtin.import_tasks: ../apt-install.yml

- name: Helper compile
  become: true
  ansible.builtin.shell: make
  args:
    chdir: /usr/share/doc/git/contrib/credential/libsecret
