---
check:
  parameter:
    - &local-machine
      group: [ local ]
      environment_name: "local"
    - &server-group
      group: [ "server", *local-machine ]
      environment_name: "product"
    - &develop-group
      group: [ "develop", *local-machine ]
      environment_name: "develop"
    - &client-group
      group: [ "client", *local-machine ]
      environment_name: "client"
    - &wsl-group
      group: [ "wsl", *local-machine ]
      environment_name: "wsl"
  hosts:
    localhost:
      group: [ *local-machine ]
      #login-option:
      #  - ansible_ssh_host: "127.0.0.1"
    kumanomi:
      group: [ *server-group ]
      login-option:
        - ansible_ssh_host: "192.168.200.16"
        - ansible_ssh_user: "awatan"
    pc2428:
      group: [ *wsl-group ]
      login-option:
        - ansible_ssh_user: "awatan"
    tuna:
      group: [ *develop-group ]
    okoze:
      group: [ *develop-group ]
    tachiuo:
      group: [ *develop-group ]
      login-option:
        - ansible_ssh_user: "jl3lam"
