---
- name: Install docker
  ansible.builtin.set_fact:
    packages:
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - docker-buildx-plugin

- name: Import installer
  ansible.builtin.import_tasks: ../apt-install.yml
