---
- name: Install docker
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - docker-buildx-plugin
    state: present
    force_apt_get: false
